### ISSUE TITLE
cannot npm run start

### ISSUE THREAD

**Issue by kabirgaire0** [Eugenoo/eCommerce#1]
there is no way for me to run the frontend. how do I fix this issue.

**npm run start**
```
`me@me:~/Documents/career/projects/myprojects0320/eCommerce/Front/vue$ npm run start

> hazaj@0.0.0 start
> vue-cli-service serve

 INFO  Starting development server...
 ERROR  Error: @vitejs/plugin-vue requires vue (>=3.2.13) or @vue/compiler-sfc to be present in the dependency tree.
Error: @vitejs/plugin-vue requires vue (>=3.2.13) or @vue/compiler-sfc to be present in the dependency tree.
    at Object.<anonymous> (/usr/local/lib/node_modules/@vue/cli-service/node_modules/vue-loader/dist/compiler.js:14:15)
    at Module._compile (node:internal/modules/cjs/loader:1364:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
    at Module.load (node:internal/modules/cjs/loader:1203:32)
    at Module._load (node:internal/modules/cjs/loader:1019:12)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@vue/cli-service/node_modules/vue-loader/dist/index.js:29:20)
    at Module._compile (node:internal/modules/cjs/loader:1364:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)`
```

**npm install @vue/compiler-sfc**
```
`me@me:~/Documents/career/projects/myprojects0320/eCommerce/Front/vue$ npm install @vue/compiler-sfc
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'amqplib@0.5.2',
npm WARN EBADENGINE   required: { node: '>=0.8 <=9' },
npm WARN EBADENGINE   current: { node: 'v20.12.1', npm: '10.5.1' }
npm WARN EBADENGINE }

removed 2 packages, and audited 357 packages in 3s

89 packages are looking for funding
  run `npm fund` for details

12 vulnerabilities (4 moderate, 4 high, 4 critical)

To address issues that do not require attention, run:
  npm audit fix

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.`
```

**Comment by Eugenoo** [comment]
you need to run npm run dev

**Comment by kabirgaire0** [comment]
> you need to run npm run dev
> 

I tried, the packages require different versions of node/npm. It's stated in the error message
